In [29]:
import numpy as np

arr_1 = np.random.randint(100,size = (10,10))

print("Array of random 10x10 is : ",arr_1)

print("Minimum is: ", np.min(arr_1))

print("Maximum is:", np.max(arr_1))

[[ 2 53 28 99 31 47 42 37  8 46]
 [90 19 87 42 24 90  1  0  1  8]
 [45 27 95 34 12 46 76 95 42 23]
 [ 0 75  9 52 97 40 69 41 38 65]
 [88 25 93 55 10 46 35 11 54 31]
 [40 51 96 83 80 21 71 52 59 50]
 [76 66 53  7 30 67 90 48 24 52]
 [66 64 52 66 23  8 36 73 90  5]
 [33 45 94 32 75  2 84 48 46 53]
 [95 96 79 45 48 10 34 46 63 58]]
0
99
